### ISSUE TITLE
facilitate indexer queries independent of client queries

### ISSUE THREAD

**Issue by Theodus** [edgeandnode/gateway#685]
With the transition away from the hosted service, the gateway must be able to make queries to the core network subgraph using indexers on the network. This requires decoupling `graph_gateway::client_query::handle_indexer_query` from `client_query`. I think this should involve having a new module, `indexer_query`, for this purpose. The new module should be usable for `client_query` and also for other network subgraph queries. The new module should not be responsible for selecting indexers.

I expect the biggest challenge to be related to reporting. Indexer query reports should no longer assume an associated client query (`ray_id` can be null, etc.).

**Comment by LNSD** [comment]
> I expect the biggest challenge to be related to reporting. Indexer query reports should no longer assume an associated client query (`ray_id` can be null, etc.).

For traceability, we should use some ID to tag the internal requests based on the [Gateway ID](https://github.com/edgeandnode/gateway/blob/5010d64a84bcd154cf774a09d81046660d01b10a/graph-gateway/src/config.rs#L35-L40) configuration parameter.

**Comment by Theodus** [comment]
I expect non-subgraph gateways to rely on the subgraph gateway for subgraph queries. The major reason for keeping indexer selection separate is that there's a bootstrapping problem for the subgraph gateway (we need a set of known indexers to initially query the network subgraph to discover the rest).

**Comment by LNSD** [comment]
> @Theodus Do we not also need indexer selection? The reason I'm thinking this is that non-subgraph gateways will need to query the network subgraph as well. There are two ways to achieve this:
> 
> 1. the gateway does these queries itself (in this case every gateway needs to essentially include a (network) subgraph gateway
> 2. the gateway queries the subgraph gateway (in this case every gateway needs to be a customer & consumer of a subgraph gateway)

As @Theodus points out, you need an "indexer discovery" mechanism/service to know who you will query. In our case, it is the Graph Network subgraph. Then, with the output of that service which is a raw list of candidates, you feed it into the candidate selection algorithm to get the final list of indexers to send requests to.

**Comment by Jannis** [comment]
I understand the bootstrapping problem. I agree that non-subgraph gateways could rely on a subgraph gateway for indexer discovery. It's a bit awkward because it makes the subgraph gateway a bottleneck/requirement for everything else to work. But as long as we can scale the subgraph gateway beyond a single operator that could be ok. Also, the non-subgraph gateway operator could run their own subgraph gateway easily. We could even define an optional "free api key" for internal use if we need it to avoid the operator subscribing to themselves. Ok, problem sorted.

@LNSD Yes, for sure. I'd like to see a short writeup of the proposed changes when you're ready because there's further modularization of `indexer_query` that will be necessary for the SDK. I want to make sure all changes make sense together.

**Comment by LNSD** [comment]
I've just opened a PR in draft mode here: #706 

This is the first iteration at this point. It covers the functionality required by the Graph gateway to serve queries.

It needs yet to be tested and integrated into the gateway code, hence the draft mode.

---

There will be a couple more iterations on top of these changes before we can generalize this into the framework.

@Jannis It would be interesting to discuss requirements so the upcoming iterations align with the data services SDK initiative.
